stages:
  - test
  - infrastructure
  - ansible

test:
  image: node:latest
  stage: test
  before_script: 
    - npm install
  script:
    - node app.js &
    - npm test
  cache:
    paths:
      - node_modules/
 
terraform_infra:
  stage: infrastructure
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - mkdir /root/.ssh
    - cp $SSH_PRIVATE_KEY /root/.ssh/id_rsa
    - chmod 0600 /root/.ssh/id_rsa
    - terraform init
  script:
    - terraform validate
    - echo "$SSH_PUBLIC_KEY"
    - terraform plan --out plan -var="ssh_public_key=$SSH_PUBLIC_KEY"
    - terraform apply --auto-approve plan
  artifacts:
    paths:
      - ./inventories/inv.ini
  cache:
    key: terraform
    paths:
      - .terraform

ansible:
  image:
    name: cytopia/ansible:latest-tools

  stage: ansible
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod -R 777 ./inventories/inv.ini
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


  script:
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ansible-playbook install.yml --check
